name: Deploy Python Application

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    environment: Prod
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: kin4stat/vk_to_tg_bot:latest

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull kin4stat/vk_to_tg_bot:latest
          docker run -e VK_TOKEN=${{ secrets.VK_TOKEN }} -e TG_TOKEN=${{ secrets.TG_TOKEN }} -e TG_CHANNEL=${{ secrets.TG_ID }} -e VK_GROUP=${{ secrets.VK_ID }} -v persistent:/persistent -d kin4stat/vk_to_tg_bot:latest